name: labelar_demo
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - autopep8
  - black
  - blas
  - cython
  - easydict=1.9
  - flake8
  - h5py
  - hdf5
  - imageio
  - intel-openmp
  - ipykernel=5.*
  - ipython=7.*
  - ipython_genutils=0.2.*
  - isort
  - jpeg
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - keras
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl_fft
  - mkl_random
  - mypy
  - nbconvert
  - nbformat
  - nomkl
  - numba
  - numpy
  - numpy-base
  - openblas
  - openblas-devel
  - opencv
  - pandoc
  - pandocfilters
  - pillow
  - pip
  - progress
  - pygments
  - pylint
  - pyparsing
  - pytest
  - python=3.7.3
  - pytorch=1.1.0
  - rope
  - scikit-image
  - scikit-learn
  - scipy=1.3.0
  - setproctitle
  - setuptools=41.0.1
  - tensorboard=1.13.1
  - tensorboardx=1.7
  - tensorflow=1.13.1
  - torchvision=0.3.0
  - tqdm
  - yacs
  - yaml
